version: '3.8'

services:
  postgres:
    container_name: postgresdb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: nestapp
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres: